version: "3.8"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      # DNS
      - 53:53
      # DHCP server
      - 67:67/udp
      - 68:68/tcp
      # HTTPS/DNS-over-HTTPS
      # - 443:443/tcp
      # DNS-over-TLS
      # - 853:853/tcp
      # DNS-over-QUIC
      # - 784:784/udp
      # DNSCrypt
      # - 5443:5443/tcp
      # - 5443:5443/udp
      # WebUI
      - 80:80/tcp
      - 443:443/tcp
      - 3000:3000/tcp
    volumes:
      - ./data/conf:/opt/adguardhome/conf
      - ./data/work:/opt/adguardhome/work
    networks:
      macvlan:
        ipv4_address: 10.203.1.203 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 192.168.10.192 # Pick same last numbers as macvlan and use "vlan bridge subnet" (10)
    restart: unless-stopped

# Here we define what networks are available to use by the services above
# Make sure to set the config of both macvlan and vlan_bridge as described in the guide.
networks:
  macvlan:
    name: adguard_macvlan
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.203.1.0/24 # Set to same subnet as your router and other devices
          ip_range: 10.203.1.203/27 # Available range from 192 to 224.
          gateway: 10.203.1.1 # This is your router IP

  vlan_bridge:
    name: adguard_vlan_bridge
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.10.0/24 # subnet for all containers 
          ip_range: 192.168.10.192/27 # for easier use, set to same range as under macvlan (192 to 224 here)
          gateway: 192.168.10.1 # for easier use, set to same last number as your router
